import DataBase as DB
import smtplib

import email.mime.multipart as MIMEMultipart
import email.mime.text as MIMEText

def send_notify_mail():
	try:
		db = DB.DataBase()
		
		db.executeSQL('call ending_in_180_days()')
		rows = []
		for r in db.fetchalldata():
			rows.append(r)

	except MySQLdb.Error, e:
		print "MySQL Error [%d]: %s" % (e.args[0], e.args[1])
		return
		
	finally:
		#db.cursor.close()
		db.close_db()

	# package message
	today = datetime.date.today()#.strftime('%Y-%m-%d')
	string_of_rows = "AUTOGENERATED MESSAGE -- DO NOT REPLY\n"
	for r in rows:
		str_r = "\n%s\n\tLandlord/Tenant: %s\n" % (r[0],r[1])
		
		end = r[3] if r[3] else r[2]
		
		if end:
			if today > end:
				str_r += "\t%s day(s) PAST end date %s, with %s options remaining\n" % (abs((today - end).days),end.strftime('%m/%d/%Y'),str(r[5]-r[4]))
			else:
				str_r += "\t%s day(s) until end date %s, with %s options remaining\n" % (abs((today - end).days),end.strftime('%m/%d/%Y'),str(r[5]-r[4]))
		else:
			str_r += "\tInvalid or missing end date!\n"
			
		string_of_rows += str_r
	string_of_rows += "\nAUTOGENERATED MESSAGE -- DO NOT REPLY"
	# end package message
	
	# send the message
	sendmail_request(string_of_rows,'Leases and Licenses ending within 180 days',to_whom='mail_list')
		
	return

def sendmail_request(msg,subject,to_whom):
	"""
	msg 	= Body of the email
	subject = Subject of the email
	to_whom = value to query the property_mailing_list on will be either 'admin' or 'mail_list'
	"""
	try: 
		db = DB.DataBase()
		db.executeSQL("select email from property_mailing_list where %s = 'Yes'" % to_whom)
		toaddrs		= [r[0] for r in db.fetchalldata()]
	except MySQLdb.Error, e:
		print "MySQL Error [%d]: %s" % (e.args[0], e.args[1])
		db.close_db()
		return	
	finally:
		db.close_db()
	
	fromaddr = 'property.database@ucr.edu' # address that will be sending the mail

	message = MIMEMultipart.MIMEMultipart()
	message['From'] 	= fromaddr
	message['To']  		= ", ".join(toaddrs)
	message['Subject'] 	= subject
	message.attach(MIMEText.MIMEText(msg))

	server = smtplib.SMTP('mx2.ucr.edu:25')
	server.starttls()
	server.ehlo("ucr.edu")
	server.sendmail(fromaddr,toaddrs,message.as_string())
	server.quit()
	return